import { validateNpcName } from "./validateNpcName.js";

import {
  calderonOccupations,
  adventuringCallings,
  calderonQuirks,
} from "../src/data/npcGeneratorData.js";

import {
  species,
  backgrounds,
} from "../src/data/open5eNpcData.js";

export function validateNpcSubmission(npc) {
  const {
    name,
    species: submittedSpecies,
    calling,
    callingType,
    background,
    quirk,
  } = npc;

  // Name moderation
  const nameValidation = validateNpcName(name);

  if (!nameValidation.isValid) {
    return {
      isValid: false,
      message: nameValidation.message,
    };
  }

  // Species must actually come from our Open5e cache
  if (!species.includes(submittedSpecies)) {
    return {
      isValid: false,
      message: "Invalid species.",
    };
  }

  // Background must actually come from our Open5e cache
  if (!backgrounds.includes(background)) {
    return {
      isValid: false,
      message: "Invalid background.",
    };
  }

  // Calling must match its type
  if (callingType === "class") {
    if (!adventuringCallings.includes(calling)) {
      return {
        isValid: false,
        message: "Invalid adventuring calling.",
      };
    }
  } else if (callingType === "occupation") {
    if (!calderonOccupations.includes(calling)) {
      return {
        isValid: false,
        message: "Invalid Calderon occupation.",
      };
    }
  } else {
    return {
      isValid: false,
      message: "Invalid calling type.",
    };
  }

  // Quirk must be one generated by AYCM
  if (!calderonQuirks.includes(quirk)) {
    return {
      isValid: false,
      message: "Invalid tragic flaw.",
    };
  }

  return {
    isValid: true,
    message: "",
  };
}